language: scala
sudo: false
jdk: oraclejdk8
script:
- sbt "project sbt-testng-interface" "+ test" "+ publishLocal" "sbt-testng-plugin/test" "sbt-testng-plugin/scripted"
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
